name: CI - Build Backend iFonte

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_USER: omini
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_ACCESS_TOKEN}}
          POSTGRES_DB: ifonte
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify
        env:
          POSTGRES_ACCESS_TOKEN: ${{secrets.POSTGRES_ACCESS_TOKEN}}